name: LumberPlot
version: 2.1
description: Define protected tree farm plots
author: ame94
main: ca.ame94.lumberplot.PluginMain
api-version: 1.15.1
depend: [WorldEdit]

commands:
    lumberplot:
        description: Modify plugin settings
        permission: lumberplot.admin
        permission-message: ยง4You are not permitted to use this plugin.
